### PR TITLE
working baroclinic test case example

### PR DESCRIPTION
**Pull request by oelbert**
**Description**
Includes an example of the moist baroclinic instability test case and resolves a couple of final notebook version mismatches

**How Has This Been Tested?**
The example notebook has been run from scratch with a newly built image

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included

### CODE REVIEW

**Review by fmalatino — APPROVED** [review]
lgtm

**Comment by FlorianDeconinck** [comment]
Great work. We really ought to have those notebooks parts of the `ci`, they are great woopsies catcher

**Review by FlorianDeconinck — APPROVED** [review]

**Comment by mlee03** [comment]
Which notebooks should be considered part of CI?  I can add them to run in the CI container.

**Comment by FlorianDeconinck** [comment]
I'd say all? Unless they take a large amount of time, but since they are example of usage they should all be checked to be working

**Comment by mlee03** [comment]
Will look into it!

**Comment by oelbert** [comment]
I think the baroclinic_example, geberate_eta_file, and stencil_definition notebooks are the most important ones

**Pull request merged**
