### PR TITLE
Update notebooks for eta file creations 

### PR DESCRIPTION
**Pull request by mlee03**
**Description**
In this PR, `generate_eta_files.ipynb` has been added.  This notebook will generate the `eta79.nc` and `eta91.nc` files that are used in tests/main.  This notebook will be used as part of CI to generate input files on-the-fly.

In addition, the notebooks `generate_eta_file_netcdf.ipynb` and `generate_eta_file_xarray.ipynb` have been removed.  Contents of `generate_eta_file_xarray.ipynb` are contained in the new notebook.   And since the files can be generated with `generate_eta_files.ipynb`, `generate_eta_file_netcdf.ipynb` has been removed.

Fixes # (issue)

**How Has This Been Tested?**
The jupyter notebook was converted to a python script (for convenience) and executed. The contents of the generated netcdf files were checked against the original data in class HybridPressureCoefficients

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included

### CODE REVIEW

**Review by fmalatino — APPROVED** [review]
lgtm

**Review by oelbert — APPROVED** [review]
Looks good, though I don't know if long-term we need to keep these as ipynb files instead of pure python?

**Comment by mlee03** [comment]
I was just thinking that especially when the goal is just to write out files, perhaps it'd be better to change move/convert the notebook to a python script in this PR.  @fmalatino, this PR is not readly

**Review by xyuan — APPROVED** [review]
thanks, this pr looks great!

**Comment by fmalatino** [comment]
I see the PR is re-opened and all tests pass, @mlee03 is this ready to be merged?

**Comment by mlee03** [comment]
'tis ready

**Pull request merged**
